database:
    host: localhost
    name: tsim_socket_server
    password: Zsax9771071
    port: "3306"
    user: root
jwt:
    secret: your-secret-key-here
logging:
    format: json
    level: info
rabbitmq:
    url: amqp://guest:guest@localhost:5672/
redis:
    url: redis://localhost:6379
server:
    port: "7001"
smpp:
    enquire_link_interval: 30s
    session_timeout: 60s
sms_monitoring:
    check_interval_minutes: 15
    maintenance_threshold: 5
    min_sms_for_check: 5
    monitoring_window: 5
websocket_url: ws://tsimasia.icell.cloud:7001/ws
