database:
  host: localhost
  port: 3306
  user: root
  password: password
  name: tsim_socket_server

jwt:
  secret: your-secret-key-here

server:
  port: 7001
websocket_url: ws://192.168.9.4:7001/ws


rabbitmq:
  url: amqp://guest:guest@localhost:5672/

redis:
  url: redis://localhost:6379

smpp:
  enquire_link_interval: 30s
  session_timeout: 60s

logging:
  level: info
  format: json 