version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tsim_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tsim_socket_server
      MYSQL_USER: tsim_user
      MYSQL_PASSWORD: tsim_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - tsim_network

volumes:
  mysql_data:

networks:
  tsim_network:
    driver: bridge 