server:
  host: "0.0.0.0"
  port: 2775
  read_timeout: 30s
  write_timeout: 30s
  max_sessions: 1000
  session_timeout: 60s
  enquire_link_interval: 30s
  tcp_keepalive: true
  tcp_keepalive_period: 30s
  tcp_linger: 0s

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  name: "tsim_socket_server"

# Redis removed - using MySQL for authentication

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "tsimcloudrouter"
  queue: "tsimcloudrouter"
  delivery_report_queue: "tsimcloud_delivery_report"

logging:
  level: "info"
  format: "text"

smpp:
  enquire_link_interval: 30s
  session_timeout: 60s 