server:
  host: "0.0.0.0"
  port: 2775
  read_timeout: 120s
  write_timeout: 120s
  max_sessions: 2000
  session_timeout: 600s
  enquire_link_interval: 90s
  tcp_keepalive: true
  tcp_keepalive_period: 90s
  tcp_linger: 10s

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  name: "tsim_socket_server"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "tsimcloudrouter"
  queue: "tsimcloudrouter"
  delivery_report_queue: "tsimcloud_delivery_report"

logging:
  level: "info"
  format: "text"

smpp:
  enquire_link_interval: 90s
  session_timeout: 600s 