-- TSIM Socket Server Database Initialization
-- This script runs when the MySQL container starts for the first time

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS tsim_socket_server CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Use the database
USE tsim_socket_server;

-- Create SMS logs table
CREATE TABLE IF NOT EXISTS sms_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    message_id VARCHAR(255) NOT NULL UNIQUE,
    msg_id VARCHAR(255),
    operator_msg_id VARCHAR(255),
    uid VARCHAR(255),
    correlation_id VARCHAR(255),
    device_id VARCHAR(255),
    device_name VARCHAR(255),
    device_imei VARCHAR(255),
    device_imsi VARCHAR(255),
    simcard_name VARCHAR(255),
    sim_slot INT,
    simcard_number VARCHAR(255),
    simcard_iccid VARCHAR(255),
    device_group_id BIGINT UNSIGNED,
    device_group VARCHAR(255),
    sitename_id BIGINT UNSIGNED,
    sitename VARCHAR(255),
    source_addr VARCHAR(255),
    destination_addr VARCHAR(255),
    message TEXT,
    message_length INT NOT NULL DEFAULT 0,
    message_encoding VARCHAR(50),
    direction VARCHAR(20) NOT NULL DEFAULT 'outbound',
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    status_code VARCHAR(50),
    retry_count INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 3,
    queued_at TIMESTAMP NULL,
    sent_at TIMESTAMP NULL,
    delivered_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    processed_at TIMESTAMP NULL,
    smpp_user_id BIGINT UNSIGNED,
    smpp_sent BOOLEAN NOT NULL DEFAULT FALSE,
    operator_name VARCHAR(255),
    operator_code VARCHAR(50),
    mcc VARCHAR(10),
    mnc VARCHAR(10),
    rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    charge DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    currency VARCHAR(10) NOT NULL DEFAULT 'TRY',
    pdu_count INT NOT NULL DEFAULT 1,
    total_cost DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    error_message TEXT,
    error_code VARCHAR(50),
    delivery_report_requested BOOLEAN NOT NULL DEFAULT TRUE,
    delivery_report_received_at TIMESTAMP NULL,
    delivery_report_status VARCHAR(50),
    processing_time_ms INT,
    queue_time_ms INT,
    is_blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
    campaign_id VARCHAR(255),
    batch_id VARCHAR(255),
    metadata JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_device_id (device_id),
    INDEX idx_sim_slot (sim_slot),
    INDEX idx_device_group_id (device_group_id),
    INDEX idx_direction (direction),
    INDEX idx_status (status),
    INDEX idx_smpp_user_id (smpp_user_id),
    INDEX idx_created_at (created_at),
    INDEX idx_destination_addr (destination_addr),
    INDEX idx_source_addr (source_addr),
    INDEX idx_device_imei (device_imei),
    INDEX idx_device_imsi (device_imsi),
    INDEX idx_sitename (sitename),
    INDEX idx_device_group (device_group),
    INDEX idx_source_username (source_username),
    INDEX idx_created_at_status (created_at, status),
    INDEX idx_created_at_direction (created_at, direction),
    INDEX idx_created_at_device_id (created_at, device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 