-- USSD Logs and SIM Cards Tables
-- This script creates the ussd_logs and sim_cards tables

USE tsim_socket_server;

-- Create ussd_logs table
CREATE TABLE IF NOT EXISTS ussd_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    device_name VARCHAR(255),
    device_imei VARCHAR(255),
    device_imsi VARCHAR(255),
    sim_slot INT,
    ussd_code VARCHAR(255) NOT NULL,
    request_message TEXT,
    response_message TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    sent_at TIMESTAMP NULL,
    received_at TIMESTAMP NULL,
    error_message TEXT,
    metadata JSON,
    device_group_id BIGINT UNSIGNED,
    device_group VARCHAR(255),
    sitename_id BIGINT UNSIGNED,
    sitename VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_session_id (session_id),
    INDEX idx_device_id (device_id),
    INDEX idx_sim_slot (sim_slot),
    INDEX idx_ussd_code (ussd_code),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_device_group_id (device_group_id),
    INDEX idx_sitename_id (sitename_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create sim_cards table
CREATE TABLE IF NOT EXISTS sim_cards (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slot_index INT NOT NULL,
    subscription_id INT NOT NULL,
    display_name VARCHAR(255),
    carrier_name VARCHAR(255),
    country_iso VARCHAR(10),
    number VARCHAR(50),
    imei VARCHAR(255),
    iccid VARCHAR(255),
    imsi VARCHAR(255),
    network_mcc VARCHAR(10),
    network_mnc VARCHAR(10),
    sim_mcc VARCHAR(10),
    sim_mnc VARCHAR(10),
    network_operator_name VARCHAR(255),
    sim_operator_name VARCHAR(255),
    roaming BOOLEAN NOT NULL DEFAULT FALSE,
    signal_strength INT,
    signal_dbm INT,
    signal_type VARCHAR(50),
    rsrp INT,
    rsrq INT,
    rssnr INT,
    cqi INT,
    network_type VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    total_delivered INT NOT NULL DEFAULT 0,
    total_sent INT NOT NULL DEFAULT 0,
    total_waiting INT NOT NULL DEFAULT 0,
    main_balance DECIMAL(10,2) NOT NULL DEFAULT 0,
    sms_balance INT NOT NULL DEFAULT 0,
    sms_limit INT NOT NULL DEFAULT 0,
    device_id BIGINT UNSIGNED,
    device_name VARCHAR(255),
    sitename VARCHAR(255),
    device_group_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_slot_index (slot_index),
    INDEX idx_subscription_id (subscription_id),
    INDEX idx_carrier_name (carrier_name),
    INDEX idx_country_iso (country_iso),
    INDEX idx_number (number),
    INDEX idx_imei (imei),
    INDEX idx_iccid (iccid),
    INDEX idx_imsi (imsi),
    INDEX idx_network_operator_name (network_operator_name),
    INDEX idx_sim_operator_name (sim_operator_name),
    INDEX idx_roaming (roaming),
    INDEX idx_is_active (is_active),
    INDEX idx_network_type (network_type),
    INDEX idx_device_id (device_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 