-- Create ussd_logs table
CREATE TABLE IF NOT EXISTS ussd_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    device_name VARCHAR(255),
    device_imei VARCHAR(255),
    device_imsi VARCHAR(255),
    sim_slot INT,
    ussd_code VARCHAR(255) NOT NULL,
    request_message TEXT,
    response_message TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    sent_at TIMESTAMP NULL,
    received_at TIMESTAMP NULL,
    error_message TEXT,
    metadata JSON,
    device_group_id INT,
    device_group VARCHAR(255),
    country_site_id INT,
    country_site VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_session_id (session_id),
    INDEX idx_device_id (device_id),
    INDEX idx_sim_slot (sim_slot),
    INDEX idx_status (status),
    INDEX idx_device_group_id (device_group_id),
    INDEX idx_country_site_id (country_site_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 